# Generated by Django 2.0.2 on 2020-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=10, verbose_name='菜单名')),
                ('menu_url', models.CharField(blank=True, max_length=30, null=True, verbose_name='菜单URL')),
                ('menu_icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='菜单图标')),
                ('parent_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='父菜单ID')),
                ('menu_level', models.IntegerField(default=1, verbose_name='菜单级别')),
            ],
        ),
    ]
